# permissions for end users to edit storefrnts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storefrnt-editor-role
rules:
- apiGroups:
  - store.example.com
  resources:
  - storefrnts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - store.example.com
  resources:
  - storefrnts/status
  verbs:
  - get
